import { Nunito } from "next/font/google";
import "./globals.css";
import Login from "./components/Login/page";
import ToasterProvider from "./providers/ToasterProvider";
import ClientOnly from "./components/ClientOnly";
import { Toaster } from "react-hot-toast";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Task App",
  description: "Task App generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider>
            <Toaster position="bottom-center" />
          </ToasterProvider>
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
